### ISSUE TITLE
Make a conda package for nanopub

### ISSUE THREAD

**Issue by raar1** [fair-workflows/nanopub#130]
During the Data SIG meeting it was suggested that we should also ship a ```conda``` package for ```nanopub```.

**Comment by svenvanderburg** [comment]
Adding a recipe on conda-forge [here](https://github.com/conda-forge/staged-recipes/pull/15870)

**Comment by svenvanderburg** [comment]
It currently breaks on the `yatiml` dependency that is not available through conda. I created https://github.com/yatiml/yatiml/issues/37 to fix that!

**Comment by raar1** [comment]
Closing as this is unlikely to get done now that the project is finished for some time
