### ISSUE TITLE
Error due to `.decode('utf-8')`

### ISSUE THREAD

**Issue by vemonet** [fair-workflows/nanopub#148]
Hi @raar1, I am trying to print a `Publication` with python 3.8 and 3.9 but I am getting the following error:

```bash
Traceback (most recent call last):
  File "drug_indications_from_gdocs.py", line 163, in <module>
    print(publication)
  File "/usr/local/lib/python3.8/site-packages/nanopub/publication.py", line 340, in __str__
    s += self._rdf.serialize(format='trig').decode('utf-8')
TypeError: decode() takes 1 positional argument but 2 were given
```

It is due to this line: https://github.com/fair-workflows/nanopub/blob/main/nanopub/publication.py#L340

I don't think the `.decode()` is necessary anymore, worst case the users can do it themselves on top of what rdflib returns

fyi I managed to print the publication using:

```python
print(publication._rdf.serialize(format='trig'))
```

**Comment by raar1** [comment]
Hi Vincent, thanks a lot for raising this and sorry for the late reply (just back from holiday now). I'm going to look into this tomorrow and possibly remove the `.decode()` as you suggest

**Comment by raar1** [comment]
Ah I see! Yes, RDFLib 6 was not released yet when we last worked on this, which I think is the only reason we have the `rdflib<6.0.0,>=5.0.0` line in the requirements.

I think we definitely want to support version 6 anyway, so I will add the dirty try catch as you suggest for now :)
I will check if the rest of the tests pass with v6 - hopefully other stuff still works.
