### ISSUE TITLE
Fix nanopub-java version that we use 

### ISSUE THREAD

**Issue by svenvanderburg** [fair-workflows/nanopub#18]
(we now automatically fetch latest)

**Comment by raar1** [comment]
Using a docker image of the nanopub-java tool is something we should probably be doing, and is likely relevant to this issue.

**Comment by svenvanderburg** [comment]
Yes that makes sense!

**Comment by svenvanderburg** [comment]
There is only one docker image on [nanopub-java docker hub](https://hub.docker.com/r/umids/nanopub-java/tags) that is younger than the latest release of nanopub-java... So I implemented this instead: https://github.com/fair-workflows/nanopub/pull/27 (it just fixes the java .jar file that is being fetched instead of latest).
