### ISSUE TITLE
Improve claim() method

### ISSUE THREAD

**Issue by svenvanderburg** [fair-workflows/nanopub#19]
Current `claim()` method is still buggy, it should be a quick way to make a claim. I.e. I (the author in profile, see https://github.com/fair-workflows/nanopub/issues/9), claim 'that tomatoes are red'.

- Change it to only accept a string that is the claim, eg 'tomatoes are red'.
- Make user of the author in the profile, see https://github.com/fair-workflows/nanopub/issues/9

**Comment by raar1** [comment]
I would suggest that we might allow it to be either a string, or alternatively a single RDF triple. We can check the type of what is passed to determine which it is.

At present the ```claim()``` method is a quick way to publish an assertion with a single triple of the form:
```
( AUTHOR, HYCL.claims, Literal(text) )
```

I'm wondering if it would be cleaner to have the assertion itself be the claim and the author doing the claiming be in the provenance subgraph. I guess then the assertion would look more like e.g.:

```
( NPURI#mystatement, RDF.type, HYCL.Statement )
( NPURI#mystatement, RDF.label, Literal(text) )
```

and the provenance graph would contain:

```
( AUTHOR, HYCL.claims, NPURI#mystatement )
```

I'll need to check with @tkuhn to see if this is a correct way of doing this. I'm also not too sure how you would allow a general triple to be the statement, unless you put it in a subgraph, or say the whole assertion is the statement (which might violate the HYCL.Statement type?).

**Comment by tkuhn** [comment]
What is the use case for this? For what will this feature be used?

I am asking because depending on the answer, you could also use AIDA sentences: https://github.com/tkuhn/aida

AIDA statements can then be represented as URI like this one: http://purl.org/aida/Malaria+is+transmitted+by+moquitoes.

This has the benefit that people are encouraged to reuse (i.e. link) existing statements and that identical statements automatically get the same identifier. Like that, you don't need separate labels and can use these statements also in subject position (which you couldn't do with literals).

**Comment by svenvanderburg** [comment]
Nice suggestion @tkuhn!
The use case is to just have a quick one-liner to do statements. It is mostly to show how simple it can be to just publish and not worry about the complex RDF that is created behind the science.

So it will be like:
```python
client = NanopubClient()
client.claim('All people are crazy')
```
Which will publish a nanopub with in the assertion:
( AUTHOR, HYCL.claims, http://purl.org/aida/all+people+are+crazy )

Where AUTHOR is the ORCID iD from profile.

**Comment by tkuhn** [comment]
I see. In that case, your original suggestion might in fact be the best, using "RDF.label". Because here we probably cannot assume that the user knows about he AIDA criteria, and might misuse the concept. Anyway, nice feature!

**Comment by svenvanderburg** [comment]
See resulting nanopublicaiton: http://test-server.nanopubs.lod.labs.vu.nl/RACwLf0MM4CPeIb3cdZbZu7ZCnCMwcCN_Mt1Ch0oofBAU

**Comment by tkuhn** [comment]
Cool! :)

But I guess `sub:_1` should be `sub:mystatement`?

**Comment by svenvanderburg** [comment]
You are right! I added the wrong link... 🙈
