### ISSUE TITLE
Add methods to NanopubClient for all possible API endpoints

### ISSUE THREAD

**Issue by svenvanderburg** [fair-workflows/nanopub#20]
See http://grlc.nanopubs.lod.labs.vu.nl//api/local/local/#/, currently we only support find_text, find_pattern, and find_things. We should add support for all the API endpoints!

**Comment by raar1** [comment]
We no longer provide a one-to-one mapping of the client's methods to the grlc endpoints anyway, so this issue is a bit out-of-date. However, ```NanopubClient._query_grlc()``` now exists, so in principle you can search any available endpoint on the nanopub servers, which essentially solves this issue.
