### ISSUE TITLE
Problem with returned concept URI from ```publish()```

### ISSUE THREAD

**Issue by raar1** [fair-workflows/nanopub#23]
Running ```publish()``` recently I notice we are now getting returned publication_info that looks like:
```
{'nanopub_uri': 'http://purl.org/np/RAM9FwSpQv90LiA9gE2l0B5dDDl2FqBzeplDYoqqgygtQ',
 'concept_uri': 'http://purl.org/np/RAM9FwSpQv90LiA9gE2l0B5dDDl2FqBzeplDYoqqgygtQ#http://purl.org/nanopub/temp/mynanopub#step'}
```

So something weird has happened to the ```concept_uri```.

**Comment by svenvanderburg** [comment]
Fixed in https://github.com/fair-workflows/nanopub/pull/26

**Comment by raar1** [comment]
#26 is merged
