### ISSUE TITLE
Adding more kwargs to from_assertion() for provenance and pubinfo subgraphs?

### ISSUE THREAD

**Issue by raar1** [fair-workflows/nanopub#36]
In principle many useful triples may be desirable in the provenance subgraph. Some of these, like wasDerivedFrom are so common they could well belong as kwargs in their own right, but there should maybe be a way to add other triples to the provenance graph at this stage?

One possibility is to simply have **kwargs in the function signature, and check the keys of that dict for any that match a given list of predicates from the http://www.w3.org/ns/prov# ontology. That would give users the ability to add any of those properties quickly, without our code ballooning up.

We have a similar issue with pubinfo, potentially, but I'm not sure that is such a common one that it necessarily needs to be in from_assertion.

**Comment by svenvanderburg** [comment]
To make this a generic approach we decided to add following arguments:
```python
provenance_triples: List(triples)
pubinfo_triples: List(triples)
```
So a user can add any triple to either the provenance or pubinfo. We will keep the common ones that we already have implemented now. We can always add more kwargs for common properties later.

**Comment by svenvanderburg** [comment]
Also fix this TODO: https://github.com/fair-workflows/nanopub/blob/055631fb13ad5b05ade4f7dfe124de6fb0c23ebf/nanopub/client.py#L244
