### ISSUE TITLE
Create user documentation

### ISSUE THREAD

**Issue by svenvanderburg** [fair-workflows/nanopub#37]
We can use [Sphinx](https://www.sphinx-doc.org/en/master/) to create user documentation to be hosted on [Read the Docs](https://readthedocs.org/).

Requirements:
- Documentation of Nanopub and NanopubClient classes (should be generated automatically based on docstrings)
- User documentation that extends the current quick start in Readme (but more complete)

**Comment by raar1** [comment]
Ideally the documentation should also cover the creation and use of author profiles, with explicit examples of it being used to publish nanopubs.

**Comment by svenvanderburg** [comment]
Suggested 'chapters':

- Using blank nodes
- Controlling publication info
- Controlling provenance graph
- Searching

**Comment by raar1** [comment]
This looks perfect. The one chapter that I would also have (although this might be fine to have only on the landing page for now) is something along the lines of "What are nanopublications? Why would I use them?"

We can write something fairly basic for that, and provide links to some of Tobias' nanopub websites etc.

**Comment by svenvanderburg** [comment]
I've updated the list!

**Comment by raar1** [comment]
Hi @tkuhn, as part of the ```nanopub``` documentation we want to say what nanopubs are. Is it ok if we copy the bottom text from [http://nanopub.org/wordpress/?page_id=65](http://nanopub.org/wordpress/?page_id=65) including the image? (Our docs already link to the nanopub.org site, for more info).

**Comment by tkuhn** [comment]
Yes, that's fine!
