### ISSUE TITLE
Add proper README

### ISSUE THREAD

**Issue by raar1** [fair-workflows/nanopub#4]
We definitely need a Quick Start section, and probably some detail about the java tool that the lib currently wraps.

Important methods to mention in readme:
```search_text```
```fetch```
```to_rdf```
```publish```
```claim```

**Comment by svenvanderburg** [comment]
The python nanopub client we arevbuilding is a higher-level (and therefore more user-friendly) way of interacting with nanopub than nanopub-java. Maybe we should also sell it more in that way.

**Comment by raar1** [comment]
Done in PR #22
