### ISSUE TITLE
Go through library and see what needs to change before full release.

### ISSUE THREAD

**Issue by svenvanderburg** [fair-workflows/nanopub#40]
- Are names clear? Not expected to change?
- Any features still to be added that change the API?

**Comment by svenvanderburg** [comment]
List of what's still missing:
- User documentation: to be implemented in #37 (but I suspect maybe more issues will run out of that)
- #36 will change API I think

I took a careful look at all code, but this is really it it seems! (Which means we wrote an awesome library ;) )

**Comment by LourensVeen** [comment]
Don't forget to check https://guide.esciencecenter.nl/#/best_practices/checklist for things to check before releasing.

**Comment by raar1** [comment]
I think issues #59, #60, #61 and #62 should be addressed, in light of what @LourensVeen has indicated. I agree that the code appears to be free from vestigial 'Dr Bob' style artifacts. However note that the linter is complaining (see #60 ) about unused imports etc but not triggering a fail, so those code issues should also be addressed.

This shouldn't take too long, I expect. User documentation could take the longest.

**Comment by LourensVeen** [comment]
Also, here's [my release procedure](https://yatiml.readthedocs.io/en/latest/development.html#making-a-release). It doesn't apply directly to this repository set-up, but maybe it will give some ideas. (This is the one for YAtiML, but my other software has a similar procedure.)

**Comment by svenvanderburg** [comment]
To be honest I think #59, #60, #61, and #62 are important but don't block a full release. They are technical debt, and fixing it is hugely important, but it won't effect a user.

**Comment by svenvanderburg** [comment]
❤️ 'Dr Bob' style artifacts

**Comment by LourensVeen** [comment]
Aren't they 'Sir Tim' artifacts here?

**Comment by raar1** [comment]
Sir Tim is a polite and considerate man, who may optionally have nanopubs attributed to him. Dr Bob, on the other hand, was a plaigarist who would end up being credited with authorship all over the place, with few options to prevent that. Dr Bob did not agree to go quietly, and it has taken some time to eradicate him from the code base. Please do raise an issue if you see that he has returned.

**Comment by svenvanderburg** [comment]
@raar1 I added a note on whether the search results dictionary make sense. I remember having a discussion on it, but don't recall the outcome. I am anyways find with keeping it as is.

**Comment by raar1** [comment]
Thanks, I will take a look and see!

**Comment by raar1** [comment]
I am going to say #76 should be done before release as it's fairly simple to do.

**Comment by raar1** [comment]
Actually it's non-blocking (non-essential) for this.

**Comment by svenvanderburg** [comment]
This seems all!
