### ISSUE TITLE
Agree a fix for the (wrong) URI returned when publishing to test server

### ISSUE THREAD

**Issue by raar1** [fair-workflows/nanopub#46]
I pulled out a snippet from what @miguel-ruano said in an issue on Nanotate:

> i made the update of nanopub in nanotate and make changes according of the new version and works perfect!!!,
> thanks for the update,
> 
> testing in test mode, i see something when publishing the nanopublication the return url is like http://purl.org/np/RAdG9VXVOBq-7Ju5H085CgynfrVlwpajLb02B-W0ss8Zc,
> when i go to url this returns 404(not found), because the nanopub not is publish in http://server.nanopubs.lod.labs.vu.nl/ if not in http://test-server.nanopubs.lod.labs.vu.nl/
> 
> seeing the nanopub code exactly in the NanopubClient publish method
> 
> the process is the following
> first sign the rdf and then publish it
> 
> in the process of sign the rdf, the code seems not know about the test enviroment and always url base is like http://purl.org/np/RAdG9VXVOBq-7Ju5H085CgynfrVlwpajLb02B-W0ss8Zc
> 
> ```
> def sign(self, unsigned_file: Union[str, Path]) -> str:
> 	unsigned_file = str(unsigned_file)
>         self._run_command(f'{NANOPUB_SCRIPT} sign ' + unsigned_file)
>         return self._get_signed_file(unsigned_file)
> ```
> 
> so when extract the nanopub uri, after publishing in test server
> 
> ```
>  @staticmethod
>  def extract_nanopub_url(signed: Union[str, Path]):
>       # Extract nanopub URL
>       # (this is pretty horrible, switch to python version as soon as it is ready)
>       extracturl = rdflib.Graph()
>       extracturl.parse(str(signed), format="trig")
>       return dict(extracturl.namespaces())['this'].__str__()
> ```
> 
> always return the same url for test or production mode, i guess that bug is in the sign method.
> 
> I hope this helps you to solve it in the future.

Can we make a quick fix for this by just modifying the wrapper methods he mentions above? Or is there something else we need to be careful about?

**Comment by svenvanderburg** [comment]
We cannot really fix this in a nice way. This is a problem on the nanopub server side, the uri http://purl.org/np/RAdG9VXVOBq-7Ju5H085CgynfrVlwpajLb02B-W0ss8Zc should point to the test server and not to the prod server. We could circumvent this by instead of returning the purl uri return the  http://test-server.nanopubs.lod.labs.vu.nl/ uri when using the test server. I would say that is a nice fix for now! The resulting nanopub will however still have references to the purl uri in its rdf, see http://test-server.nanopubs.lod.labs.vu.nl/RApAfPWGsuUp4WFz97s8_pm1_cL5Vl7yEjcZvGALYMtZM for example.

**Comment by raar1** [comment]
Yes, it is true that this will not fix the problem of the URIs in the nanopub being wrong...

What if instead we changed the ```fetch``` method so that you can specify ```from_test_server=True``` and it modfies the URI accordingly? It's still ugly, of course, but at least we're not claiming a URI for nanopubs that is different from the one they actually have.

Perhaps it is desired behaviour for publications to the test server to (otherwise) look exactly as they would on a normal server? Alternatively, I guess it is the java version that would need the functionality to return a test-server URI in certain cases, but I worry about overcomplicating things.

@tkuhn would it be awkward to give the ```np``` (java) tool an option to use e.g. the test-server URI as the base instead of ```purl.org```? Or is the current behaviour preferable?

**Comment by svenvanderburg** [comment]
Yeah we could add a `from_test_server` arg to `fetch` method.

**Comment by tkuhn** [comment]
The problem here is with fetching when the nanopub was published only to the test server. Am I understanding this correctly?

**Comment by raar1** [comment]
@tkuhn yes, exactly. If it is only available on the test servers then a regular fetch will not find it (since the URI will not resolve to the test server location), but I think we should think of this being by design. We don't want having the option of a test server to complicate the rest of the nanopub infrastructure. I think if people are publishing nanopubs to the test server, then this is an unusual condition, and they need to specify in the ```fetch()``` method that this nanopub is only expected to exist on the test server. That would be the simplest approach.

**Comment by svenvanderburg** [comment]
Might be fixed with #48, specifically this line:
https://github.com/fair-workflows/nanopub/blob/63fc2ce1087aeb6f642688ed3c768e744497a58c/nanopub/client.py#L174

**Comment by svenvanderburg** [comment]
Woops, I accidentally closed this. @raar1 NanopubClient.fetch now can also fetch from test server. Does that fix this issue or do you also want NanopubClient.publish to return the correct uri when use_test_server=True ?

**Comment by raar1** [comment]
This is the right behaviour IMO. A nanopub created in this way may be on the normal nanopub servers, on the test server, or on all of the above. It now checks the normal servers first, and if not there (and client is set to use test server) it checks the test server last.
