### ISSUE TITLE
Add README documentation for behaviour of rdflib blank nodes

### ISSUE THREAD

**Issue by raar1** [fair-workflows/nanopub#53]
The ```nanopub``` library does useful things when ```rdflib``` blank nodes (```BNode```) are passed. From the ```from_assertion``` docstring:

```
        Any blank nodes in the rdf graph are replaced with the nanopub's URI, with the blank node name
        as a fragment. For example, if the blank node is called 'step', that would result in a URI composed of the
        nanopub's (base) URI, followed by #step.
```

This is quite important behaviour. Something about this should be in the README Quick Start section.

**Comment by svenvanderburg** [comment]
@raar1 I've added a little bit about this to the readme here: https://github.com/fair-workflows/nanopub/pull/52/files . You think this fixes this issue?

**Comment by raar1** [comment]
Yes, this looks good now!
