### ISSUE TITLE
Test system undocumented

### ISSUE THREAD

**Issue by LourensVeen** [fair-workflows/nanopub#59]
This repository doesn't seem to have developer's documentation. In particular, I had to dive into the GitHub Actions definitions to figure out how to run the test suite. This should be documented in a CONTRIBUTING.rst file.

Can I perhaps suggest that you rebase the repository onto the [NLeSC Python template](https://github.com/NLeSC/python-template)? It's easier if you use it from the start, but I have successfully ported an existing repository over before. It will supply you with a bunch of pre-made configuration, saving a lot of time. And it makes it so that running the test suite is a single `python setup.py test` rather than a whole list of commands, which makes development a lot easier.

**Comment by raar1** [comment]
Good point, yes. Although I note that the NLeSC Python template's build status is failing, which I believe is contrary to best practices ;)

**Comment by raar1** [comment]
@LourensVeen I suspect we may need to update the NLeSC template at some point, if I'm understanding things correctly. I get the following message with ```python setup.py test```:

```
 python3 setup.py test
running test
WARNING: Testing via this command is deprecated and will be removed in a future version. Users looking for a generic test entry point independent of test runner are encouraged to use tox.
```

This seems to be related to issues like this:
[https://github.com/pypa/setuptools/issues/1684](https://github.com/pypa/setuptools/issues/1684)

Not sure what to choose instead, really. We could just say 'type ```pytest``` to run tests' instead?

**Comment by LourensVeen** [comment]
Ah, interesting! I have actually run into problems with `pytest-mypy` with this, since `setup.py test` uses easy_install to install the dependencies, and easy_install seems to not understand the `py.typed` file which signals that the module has type annotations, so `pytest-mypy` cannot check the types, which is annoying. So a replacement that uses `pip` would be fine with me.

I think this should be picked up for the template though, if `setup.py test` is deprecated then we should have a new standard for NLeSC, and the template should be updated to match that. And then we can do the same in our repos. So shall we make an issue for this in the template repo?

**Comment by raar1** [comment]
Good idea - I can just add a modified version of what I posted above as an issue perhaps?

**Comment by raar1** [comment]
OK, I've raised an issue here: [https://github.com/NLeSC/python-template/issues/72](https://github.com/NLeSC/python-template/issues/72). Let's see what others say.

**Comment by LourensVeen** [comment]
Ah, there's actually an issue that mentions this for the Guide already: https://github.com/NLeSC/guide/issues/220. I responded to that, but I don't recall noticing this `setup.py test` issue, but it's in it.

**Comment by raar1** [comment]
Ah yes, you're right. Should I leave the python-template issue up then? Or would you guys normally prefer to close it and concentrate all discussion in the NLeSC guide repo instead?

**Comment by LourensVeen** [comment]
Well, both repos need fixing, so having an issue in each is good I think. Maybe add a link to the guide issue from the template issue?

**Comment by raar1** [comment]
Yep, good point. Have done so now.

**Comment by raar1** [comment]
I've added various bits of documentation, CONTRIBUTIONS.md, code of conduct etc. We mention the test system, flake8 and automation upon PR. It's not super detailed, but it will do for now. When the NLeSC guide etc gets updated with the new "preferred" way of doing tests, I will open a new issue to update the test system here.
