### ISSUE TITLE
Refactor Nanopub module

### ISSUE THREAD

**Issue by svenvanderburg** [fair-workflows/nanopub#6]
Initially raised by @raar1: https://github.com/fair-workflows/fairworkflows/issues/74
At present the ```Nanopub``` module contains static methods for publishing, searching, fetching etc of nanopubs. The latter two return ```NanopubObj``` objects. This whole approach is messy and should be refactored into something neater.

Possibilities:
1. A ```NanopubClient``` instance, containing these methods (now no longer static).
2. A ```Nanopub``` class, in a similar vein to ```FairStep```. Contains and constructs its own RDF. Has search and fetch methods that load the rdf directly into its own encapsulated rdf. Has a publish method that publishes its own rdf.

Other approaches? Pros and Cons?

**Comment by raar1** [comment]
I think this is all solved by #74
