### ISSUE TITLE
Running pytest --cov overwrites ~/.nanopub

### ISSUE THREAD

**Issue by LourensVeen** [fair-workflows/nanopub#61]
Some component of the test suite overwrites the user's profile in ~/.nanopub. This is probably not good, considering that it contains their keys. Also, it makes it impossible to run the test suite twice, unless you recreate your profile, because the test suite needs a valid profile in ~/.nanopub to run.

Running the test suite should not touch anything in the user's home directory, read or write. Use pytest's tmpdir!

**Comment by svenvanderburg** [comment]
Yes, this is really bad...
