### ISSUE TITLE
CI not enabled for pull requests

### ISSUE THREAD

**Issue by LourensVeen** [fair-workflows/nanopub#62]
The `nanopub.yml` workflow only triggers on pushes, not on pull requests. This is no problem for a PR from a local branch, since it will run on push for that, but it doesn't check PRs from a fork of the repo, e.g. PRs made by external contributors.

**Comment by LourensVeen** [comment]
Also, you may want to only push coverage to coveralls for the `main` branch, not for branch commits of PRs.

**Comment by svenvanderburg** [comment]
I disabled it because it would do double builds on pushes to pull requests, but I didn't think of external contributors (even though we are of course expecting loads of them)
