### ISSUE TITLE
Add a changelog

### ISSUE THREAD

**Issue by svenvanderburg** [fair-workflows/nanopub#63]
Add a changelog according to: https://keepachangelog.com/en/1.0.0/
I suggest tracking changes from version 1.0.0 😄

**Comment by raar1** [comment]
Yes, this is a good idea.

**Comment by raar1** [comment]
I've added an empty one in PR #67 so we don't forget. I note that tracking changes was always a lot easier to do with github projects, since you could look up the list of issues that constituted a given release. I may start using that again...
