### ISSUE TITLE
Add software quality checklist

### ISSUE THREAD

**Issue by raar1** [fair-workflows/nanopub#76]
Might as well get the FAIR software badge to full.

https://fair-software.eu/recommendations/checklist

**Comment by svenvanderburg** [comment]
I added one: https://bestpractices.coreinfrastructure.org/en/projects/4491. The main things we are not passing for is security and vulnerability, which to be honest are not super important at this point in time. I am not an expert, but I don't expect a lot of vulnerabilities in this software.

I updated the badges (directly to main 🏴‍☠️ )

**Comment by svenvanderburg** [comment]
@raar1 can you check and see if you like it, than close the issue?

**Comment by raar1** [comment]
Great, thanks. One thing that does seem odd is this:
```
Non-trivial license location file in repository: https://github.com/fair-workflows/nanopub/blob/main/LICENSE.
```
There's nothing non-trivial about being located in the root of the repo, where licenses always are. Does it expect the URL to be different in some way?

**Comment by raar1** [comment]
Hmm, just checked several projects on [https://bestpractices.coreinfrastructure.org/en/projects](https://bestpractices.coreinfrastructure.org/en/projects) and it seems like it just always complains about 'non-trivial' locations, with no explanation why. Anyway, doesn't matter - this looks good so I'm closing the issue.
