### ISSUE TITLE
Disemmination of nanopub library upon release

### ISSUE THREAD

**Issue by raar1** [fair-workflows/nanopub#78]
- [x] Blog post? Tweet about it?
- [x] Send round to nanopub community mailing list (maybe @tkuhn can help with this)
- [x] Workshop
- [x] Research Software Directory
- [x]  Presentation to Data SIG
- [x] Update [Project Page](https://www.research-software.nl/projects/1382)

**Comment by tkuhn** [comment]
If you are subscribe to the nanopub mailing list, you should be able to send it there yourself. I think it's good if the list members see some other names on the emails than just mine :)

**Comment by raar1** [comment]
@tkuhn Yes, that would indeed be a good idea. I'm not actually sure I am subscribed to that mailing list, I think you may just have forwarded the last email to me...?

**Comment by tkuhn** [comment]
You can subscribe here: https://trac.nbic.nl/mailman/listinfo/nanopub-users

**Comment by raar1** [comment]
Project page updated. Closing issue now
