### ISSUE TITLE
Retracting Nanopubs does not complete and retracts the same Nanopubs multiple times (aka. retracted nanopubs should not be retruned by default)

### ISSUE THREAD

**Issue by vemonet** [fair-workflows/nanopub#84]
My goal was to retract all nanopubs with `<https://w3id.org/biolink/vocab/ChemicalToDiseaseOrPhenotypicFeatureAssociation>` as Object. There a few thousands (probably between 2k and 5k nanopubs like this)

I am using this piece of code:
```python
np_client = NanopubClient()

results = np_client.find_nanopubs_with_pattern(
    obj='https://w3id.org/biolink/vocab/ChemicalToDiseaseOrPhenotypicFeatureAssociation'
    )
print(results)

for nanopub in results:
    print(nanopub['np'])
    np_client.retract(nanopub['np'], force=True)
```

When running my script it retracts a certain number of Nanopubs, but not all of them, probably due to internal limits

The issue is when I rerun the script to retract the rest that has not been retracted: it will start again from the already retracted Nanopubs, and fail to retract the one still not retracted

* Properly retracted:
![Screenshot from 2020-12-09 14-18-34](https://user-images.githubusercontent.com/3778439/101636046-0b265b80-3a2b-11eb-9057-64a75233716e.png)

* Not properly retracted:

![Screenshot from 2020-12-09 14-38-12](https://user-images.githubusercontent.com/3778439/101636878-3bbac500-3a2c-11eb-824a-8acfbdd68228.png)

When checking out the GRLC APIs SPARQL query and the Nanopub python lib code I can see that most calls does not filter out retracted nanopublications

From my point of view, Iw ould have expected that most calls ignore all retracted nanopublications by default (actually would expect this for basically all calls, wherever they are implemented in GRLC or nanopub libs)

And ideally the user should be able to define a parameter to enable getting retracted nanopublications

Some remark about retraction documentation have also been posted here: https://github.com/fair-workflows/nanopub/issues/83

**Comment by raar1** [comment]
Thank you for testing and for the suggested fix. I completely agree that this is unexpected behaviour for the majority of users.

@tkuhn would it be a problem if we modify most (or all?) the existing GRLC API endpoints to filter for retracted nanopublications by default? Or does something else currently depend on those remaining as they are, in which case we could add new endpoints to get this behaviour?

**Comment by raar1** [comment]
> When running my script it retracts a certain number of Nanopubs, but not all of them, probably due to internal limits

Ah yes, the search methods of the python library all have an optional ```max_num_results``` argument which is 1000 by default. The behaviour this was trying to solve is that users would be confused at how long the query was taking to return. But perhaps this is too buried, and the default should be to return all?

**Comment by vemonet** [comment]
Yep, "return all" as default and add a limit as parameter (needing to add a param to unlock the unlimited is also find for me if you want to avoid heavy queries by default)

**Comment by tkuhn** [comment]
The find_signed_* calls give you a column that indicates whether the nanopub has been retracted. I tried to make this also an input argument but that doesn't seem to be possible (for boring technical reasons of the SPARQL templating). But you could just filter them out on the client side.

**Comment by vemonet** [comment]
I am using `find_nanopubs_with_pattern` but it does not returns retraction infos

You can expect a lot of people will make mistake when publishing, and as a user I don't want to spend half of my nanopublishing time working to go through retracted nanopubs

1. I would expect that all calls would ignore retracted nanopubs
2. And have some calls specific for retracted nanopublications (`find_retracted_with_pattern`)

**Comment by vemonet** [comment]
`find_nanopubs_with_pattern` via the python lib returns a JSON like this:

```json
[{'np': 'http://purl.org/np/RAuAGF_Zj1XlOzN_zrEthZxVbbvUCa2Jmm880Fgm84vrA', 'description': '', 'date': '2020-12-08T16:17:34.250Z'}, {'np': 'http://purl.org/np/RAJbVGO4mmv3oxqKTylvS_ZEzM27jLhOOxYJGdxSq2hko', 'description': '', 'date': '2020-12-08T16:17:38.610Z'}]
```

**Comment by svenvanderburg** [comment]
@tkuhn Ideally we would like simple grlc endpoints  for the search methods we currently support: (find_nanopubs_with_pattern, find_nanopubs_with_text, find_things) that filters the retracted nanopublications, for these reasons:

- We want the client to be a thin wrapper around the endpoint, so all functionality is server-side. We don't want to add functionality to the client, it would be a workaround for functionality that the server is missing.
- If we request a bunch of nanopubs then most of the returned nanopubs will be retracted. The returned data that will be returned will be huge over time.

**Comment by tkuhn** [comment]
I totally see your points. But there are a number of technical obstacles:

- For signed nanopublications, only retractions that are signed with the same public key are considered valid. For unsigned nanopublications, however, there is no way to find out whether a retraction is legit. Filtering out all nanopublications that were retracted by *somebody* means that it's very easy to disrupt any system using it by retracting other people's nanopublications. That's why only `find_signed_nanopubs...` has the retracted column.

- Checking for retractions in other nanopublications adds complexity to the query. It works for the `find_signed_nanopubs...` queries because just a small fraction of all nanopublications are signed, but would most probably slow things down too much for `find_nanopubs...`. This can be solved, and will have to be solved in the future anyway, but it's not trivial. grlc and SPARQL are some limiting factors here.

But I can look into the filtering again for the `find_signed_nanopubs...` again, and try to add it also as an input parameter.$

For your applications, is it important to also support unsigned nanopublications, or could you restrict yourself to signed ones? Then you could switch to `find_signed_nanopubs...` and use filtering if I manage to implement it.

**Comment by vemonet** [comment]
Thanks for the details! Indeed it could be a challenge to scale the retracted for signed and non signed nanopubs

On our side we would like to restrict to signed nanopubs anyway (even more if it speeds up the processing)

> But I can look into the filtering again for the find_signed_nanopubs... again, and try to add it also as an input parameter.

The easy, "not so dirty" way, could be just creating a new grlc call `find_signed_valid_nanopubs` with the filtering on retracted nanopubs

It will be interesting also to compare runtimes of queries with/without retracted to see how we can improve the SPARQL filtering

**Comment by svenvanderburg** [comment]
@tkuhn fair points! I agree with @vemonet to either add filtering to the find_signed_nanopubs endpoint or create a new endpoint that does that. While we wait for this we could already implement a `find_signed_valid_nanopubs` that filters out retracted nanopubs using the workaround with the `retracted` column.

**Comment by tkuhn** [comment]
OK, I am still trying to find a way how I can make this a parameter of `find_signed_nanopubs...`, but if I don't manage I will add `find_signed_valid_nanopubs...` calls.

**Comment by tkuhn** [comment]
OK, `find_valid_signed_*` are now available (I put the `valid` in front of `signed` in the names). So far only on http://grlc.nanopubs.lod.labs.vu.nl/ and http://130.60.24.146:7880/.

@vemonet you can run `./update.sh` on the Maastricht node to update that one too. As soon as the other nodes update, this will become available there too (but I don't want to annoy them with updating requests too often).

Does that look good?

**Comment by vemonet** [comment]
Seems good!

http://grlc.np.dumontierlab.com/api/local/local/#/default/get_find_valid_signed_nanopubs_with_pattern

The query I tried worked well, I will try it more in depth asap!

Thanks a lot for such a quick reaction!

@svenvanderburg I guess we just need the corresponding function in the python lib :innocent: 

Probably alongside `find_nanopubs_with_pattern` https://github.com/fair-workflows/nanopub/blob/main/nanopub/client.py#L72 

Let me know if you have the time to do it, otherwise I could do it quite easily next week and pull request (it seems quite straightforward with the `_search` function)

**Comment by svenvanderburg** [comment]
@tkuhn great! Nice that you picked it up so soon! 👍 
I created #92 to implement this client-side. @vemonet it would be really awesome if you could pick this up, it would make us incredibly happy to have 'external' collaborations :) (make sure to checkout [CONTRIBUTING.md](https://github.com/fair-workflows/nanopub/blob/main/CONTRIBUTING.md)) If that doesn't work out for you we could pick it up this sprint and then release it end of next week.

**Comment by vemonet** [comment]
This issue is resolved for me, thanks a lot for the help implementing this fix! (cf. https://github.com/fair-workflows/nanopub/issues/92)

**Comment by svenvanderburg** [comment]
@vemonet we did some changes in v1.1.0 and v1.2.0 that affect this:
* `filter_retracted` option to methods of `NanopubClient` that allows searching for publications 
    that are note retracted. For these methods:
    - `find_nanopubs_with_text`
    - `find_nanopubs_with_pattern`
    - `find_things`
* search methods of `NanopubClient` return iterator instead of list

So the separate methods for searching on 'valid' nanopublications as introduced by #92 were refactored again into just a `filter_retracted` option.

If you want to test: `pip install nanopub --upgrade`
