### ISSUE TITLE
max_num_results default is unclear/confusing

### ISSUE THREAD

**Issue by raar1** [fair-workflows/nanopub#85]
I'm making a separate issue for something identified in #84

> When running my script it retracts a certain number of Nanopubs, but not all of them, probably due to internal limits
>
> The issue is when I rerun the script to retract the rest that has not been retracted: it will start again from the already retracted Nanopubs, and fail to retract the one still not retracted

Vincent searches for all nanopubs matching a certain pattern (in order to retract them) but is surprised when only a limited subset are retracted. The cause of this is the ```max_num_results``` optional parameter in all ```nanopub```'s search methods, which by default is 1000.

Originally this was intended to make naive searches (by new users) return in a reasonable time, since the list can be very long. But now I think it might be confusing because users expect all results to be returned by default.

**Comment by svenvanderburg** [comment]
#89 makes this obsolete.
