### ISSUE TITLE
permission denied when creating nanopub-java jar file

### ISSUE THREAD

**Issue by svenvanderburg** [fair-workflows/nanopub#88]
When trying to publish using the nanopub library when it is installed in a non-user directory we get a `RunTimeError` with:
```
Warning: Failed to create the file  
Warning: /usr/local/lib/python3.8/dist-packages/nanopub/nanopub-1.32-jar-with-d ependencies.jar: Permission denied
```
We need to download the `nanopub-java` file to a different location than the installation folder so that we have access to it. A good candidate would be the `~/.nanopub` folder.

**Comment by raar1** [comment]
In another conversation Lourens suggested using ```JPype``` if we wanted to just run the JAR without the thin bash wrapper, so that's something to look into. Could potentially help with #97 too.

**Comment by Thrameos** [comment]
JPype is primarily used when you wish to open a jar file with Python and execute operations for the duration of the Python session.   It features high speed memory transfers and direct access to all exposed methods with built in wrappers to give a Python like feel to Java classes.   You can even implement Java classes from within Python and install them into Java callback hooks such as lambdas.  The cost being Java and Python will be married at the process level, so there is a fair amount of overhead.

JPype is less applicable if you wish to start up the jvm for a single transaction and then stop it.  Other bridge codes like Py4j are better for transactal communications as you can start or stop the jvm.  But Py4j uses sockets so the communications are more limited and less integrated than JPype.

There are other bridge codes but they are less developed, less stable or not active projects currently.

So it really depends on how you wish to use the JVM as to which is the best choice.  Hope yhis helps.

**Comment by raar1** [comment]
Many thanks @Thrameos, this is indeed a useful explanation. JPype would then not really be appropriate for the proposed usage. We will also take a look at Py4j, so thanks for that suggestion too!
