### ISSUE TITLE
Check if nanopub works on Windows?

### ISSUE THREAD

**Issue by raar1** [fair-workflows/nanopub#97]
With the current ```np``` and JAR file installation (and use of ```curl```) it seems likely that Windows will choke on this. I think potentially a large fraction of the nanopub community who might use this tool could be running Windows, so we should check that it works there.

**Comment by svenvanderburg** [comment]
I did some changes in #107 to try this out, but it seems like `nanopub-java` is not supported on windows. I've raised in issue for that: https://github.com/Nanopublication/nanopub-java/issues/8. This is blocked while we await a response there. An alternative would be to create our own python version (which would also save us some python-java bridging hassle).
